spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://jaeger.cedesistemas.local:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: ${spring.application.name}
    description: gateway service
    port: ${server.port}
    version: 1.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka.cedesistemas.local:8761/eureka/

zuul:
  prefix: /cedesistemas
  routes:
    commerce:
      path: /commerce/**
      serviceId: commerce-service
    registration:
      path: /registration/**
      serviceId: registration-service
    social:
      path: /social/**
      serviceId: social-service

ribbon:
  eureka:
    enabled: true